//! Per-test coverage runner shim.
//!
//! Invoked by cargo/nextest through `CARGO_TARGET_<TRIPLE>_RUNNER`. Cargo sets
//! that var to `<cargo-affected> runner-shim` and calls it with the test binary
//! and its args:
//!
//! ```text
//! cargo-affected runner-shim <test-binary> <test-args…>
//! ```
//!
//! The shim recovers the test name from `--exact <name>`, looks up the
//! invoking binary's stable `binary_id` via a path → id map serialized by
//! `collect` (env `CARGO_AFFECTED_BINARY_MAP`), points `LLVM_PROFILE_FILE` at
//! a per-test subdirectory under `CARGO_AFFECTED_PROFRAW_BASE`, writes a
//! sidecar `meta` file (test name + binary path + binary_id), then `exec`s the
//! test binary. No other setup — nextest and cargo already provide the full
//! test environment.
//!
//! The map is regenerated by `collect` immediately before invoking
//! `cargo nextest run`, so its paths reflect cargo's current build output. If
//! the path lookup misses, that's a hard error — callers shouldn't catch it
//! by guessing.
//!
//! The subdir name includes the binary_id so two tests that share a name
//! across different binaries (e.g. a `builds` test in `mock-stub` and
//! `wt-perf`) get independent storage — without this their profraws and
//! coverage mappings collide and one silently wins.
//!
//! Unix-only (uses `execvp`). Windows isn't supported.

use std::collections::HashMap;
use std::os::unix::process::CommandExt;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Entry point. `args` is everything after `runner-shim` on argv:
/// `[<test-binary>, <test-args…>]`.
///
/// Never returns — either `exec`s the test binary or exits with an error.
pub fn run(args: &[String]) -> ! {
    let Some((binary, rest)) = args.split_first() else {
        eprintln!("cargo-affected runner-shim: missing test binary argument");
        std::process::exit(2);
    };

    if let Some(name) = find_exact(rest) {
        let base = std::env::var("CARGO_AFFECTED_PROFRAW_BASE").unwrap_or_else(|_| {
            eprintln!("cargo-affected runner-shim: CARGO_AFFECTED_PROFRAW_BASE not set");
            std::process::exit(2);
        });
        let map_path = std::env::var("CARGO_AFFECTED_BINARY_MAP").unwrap_or_else(|_| {
            eprintln!("cargo-affected runner-shim: CARGO_AFFECTED_BINARY_MAP not set");
            std::process::exit(2);
        });
        let binary_path = PathBuf::from(binary);
        let binary_id = resolve_binary_id(Path::new(&map_path), &binary_path).unwrap_or_else(|e| {
            eprintln!(
                "cargo-affected runner-shim: failed to resolve binary_id for {}: {e}",
                binary_path.display()
            );
            std::process::exit(2);
        });

        let subdir = format!("{}__{}", sanitize(&binary_id), sanitize(&name));
        let dir = Path::new(&base).join(subdir);
        if let Err(e) = std::fs::create_dir_all(&dir) {
            eprintln!(
                "cargo-affected runner-shim: failed to create {}: {e}",
                dir.display()
            );
            std::process::exit(2);
        }
        // Sidecar — post-pipeline reads test name + binary path + binary_id
        // from here instead of inverting sanitize() or fanning out across
        // binaries. Format: `<test-name>\n<binary-path>\n<binary-id>\n`.
        let _ = std::fs::write(
            dir.join("meta"),
            format!("{name}\n{binary}\n{binary_id}\n"),
        );
        std::env::set_var("LLVM_PROFILE_FILE", dir.join("%p-%m.profraw"));
    }
    // No --exact: likely --list / --help / discovery. Passthrough without coverage.

    let err = Command::new(binary).args(rest).exec();
    eprintln!(
        "cargo-affected runner-shim: exec {} failed: {err}",
        binary
    );
    std::process::exit(127);
}

/// Find the value of `--exact <name>` or `--exact=<name>` in args.
fn find_exact(args: &[String]) -> Option<String> {
    let mut it = args.iter();
    while let Some(a) = it.next() {
        if a == "--exact" {
            return it.next().cloned();
        }
        if let Some(v) = a.strip_prefix("--exact=") {
            return Some(v.to_string());
        }
    }
    None
}

/// Make a test name or binary id safe for use as a single filesystem directory
/// component.
///
/// Keeps `::`, alphanumerics, `_`, `-`, `.`. Replaces everything else with `_`.
/// Rust test names and nextest binary ids are `::`-joined identifiers, so
/// ordinary names pass through unchanged and collisions are unlikely in
/// practice.
pub fn sanitize(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for c in name.chars() {
        if c.is_ascii_alphanumeric() || c == ':' || c == '_' || c == '-' || c == '.' {
            out.push(c);
        } else {
            out.push('_');
        }
    }
    out
}

/// Look up the binary's nextest `binary_id` in the map written by `collect`.
///
/// The map is `HashMap<binary_path, binary_id>` regenerated by `collect`
/// immediately before invoking `cargo nextest run`, indexed by the stable
/// `(package, target, kind)` triple cargo emits in its JSON.
///
/// Resolution order:
/// 1. Exact path lookup, or canonicalized-path lookup.
/// 2. Basename-target-name fallback: cargo's hash suffix can still drift
///    between the pre-run listing and the actual run (CI rust-cache restore
///    races, build-script env sensitivity, etc). Strip the `-<16hex>` suffix
///    and match by target name. Accept only when the resulting candidate set
///    is unique — we'd rather hard-fail than silently attribute coverage to
///    the wrong binary.
fn resolve_binary_id(map_path: &Path, binary_path: &Path) -> anyhow::Result<String> {
    let json = std::fs::read_to_string(map_path).map_err(|e| {
        anyhow::anyhow!("reading binary map at {}: {e}", map_path.display())
    })?;
    let map: HashMap<String, String> = serde_json::from_str(&json)
        .map_err(|e| anyhow::anyhow!("parsing binary map {}: {e}", map_path.display()))?;

    let as_str = binary_path.to_str().unwrap_or("");
    if let Some(id) = map.get(as_str) {
        return Ok(id.clone());
    }
    if let Ok(canon) = std::fs::canonicalize(binary_path) {
        if let Some(id) = canon.to_str().and_then(|s| map.get(s)) {
            return Ok(id.clone());
        }
    }

    let probe = binary_path
        .file_name()
        .and_then(|n| n.to_str())
        .map(target_name);
    if let Some(probe) = probe {
        let mut candidates: Vec<&str> = map
            .iter()
            .filter(|(key_path, _)| {
                Path::new(key_path)
                    .file_name()
                    .and_then(|n| n.to_str())
                    .map(target_name)
                    == Some(probe)
            })
            .map(|(_, id)| id.as_str())
            .collect();
        candidates.sort();
        candidates.dedup();
        match candidates.as_slice() {
            [only] => return Ok((*only).to_string()),
            many @ [_, _, ..] => {
                return Err(anyhow::anyhow!(
                    "binary not found in map (path: {}); target-name basename \
                     fallback ambiguous — {} candidates share target name {:?} \
                     ([{}]); re-run `cargo affected collect`",
                    binary_path.display(),
                    many.len(),
                    probe,
                    many.join(", "),
                ))
            }
            [] => {}
        }
    }

    Err(anyhow::anyhow!(
        "binary not found in map (path: {}); cargo's build output drifted \
         between collect's pre-run listing and the shim invocation — re-run \
         `cargo affected collect`",
        binary_path.display(),
    ))
}

/// Strip cargo's `-<16hex>` hash suffix from a deps/ basename.
///
/// `worktrunk-e19bc0c52c763540` → `worktrunk`
/// `builds-8cd2602cd0d82929` → `builds`
/// `worktrunk-build-script-build` (no 16-hex tail) → unchanged
fn target_name(basename: &str) -> &str {
    let bytes = basename.as_bytes();
    if bytes.len() < 17 || bytes[bytes.len() - 17] != b'-' {
        return basename;
    }
    let hash = &basename[basename.len() - 16..];
    if hash.bytes().all(|b| matches!(b, b'0'..=b'9' | b'a'..=b'f')) {
        &basename[..basename.len() - 17]
    } else {
        basename
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn find_exact_space_form() {
        let args: Vec<String> = ["--nocapture", "--exact", "foo::bar", "--test-threads=1"]
            .into_iter()
            .map(String::from)
            .collect();
        assert_eq!(find_exact(&args).as_deref(), Some("foo::bar"));
    }

    #[test]
    fn find_exact_equals_form() {
        let args: Vec<String> = ["--exact=foo::bar", "--nocapture"]
            .into_iter()
            .map(String::from)
            .collect();
        assert_eq!(find_exact(&args).as_deref(), Some("foo::bar"));
    }

    #[test]
    fn find_exact_missing() {
        let args: Vec<String> = ["--list", "--format=terse"]
            .into_iter()
            .map(String::from)
            .collect();
        assert_eq!(find_exact(&args), None);
    }

    #[test]
    fn sanitize_passthrough() {
        assert_eq!(sanitize("math::tests::test_add"), "math::tests::test_add");
        assert_eq!(sanitize("plain_name"), "plain_name");
        assert_eq!(sanitize("mock-stub::builds"), "mock-stub::builds");
    }

    #[test]
    fn sanitize_replaces_hostile_chars() {
        assert_eq!(sanitize("a/b"), "a_b");
        assert_eq!(sanitize("a\\b"), "a_b");
        assert_eq!(sanitize("a b"), "a_b");
    }

    #[test]
    fn resolve_binary_id_exact_match() -> anyhow::Result<()> {
        let dir = tempfile::tempdir()?;
        let map_path = dir.path().join("map.json");
        let mut map: HashMap<String, String> = HashMap::new();
        map.insert(
            "/tmp/target/debug/deps/foo-abc123".to_string(),
            "mycrate::foo".to_string(),
        );
        std::fs::write(&map_path, serde_json::to_string(&map)?)?;

        let id = resolve_binary_id(&map_path, Path::new("/tmp/target/debug/deps/foo-abc123"))?;
        assert_eq!(id, "mycrate::foo");
        Ok(())
    }

    #[test]
    fn resolve_binary_id_canonical_match() -> anyhow::Result<()> {
        // Cargo may pass a path that canonicalizes to one stored in the map
        // (relative path, symlink). Lookup must succeed via canonicalize().
        let dir = tempfile::tempdir()?;
        let canonical = dir.path().canonicalize()?;
        let binary = canonical.join("foo-abc123");
        std::fs::write(&binary, b"")?;

        let map_path = dir.path().join("map.json");
        let mut map: HashMap<String, String> = HashMap::new();
        map.insert(binary.to_str().unwrap().to_string(), "mycrate::foo".into());
        std::fs::write(&map_path, serde_json::to_string(&map)?)?;

        // Force a lookup with a non-canonical path (via the tempdir's symlinky
        // /var/folders form on macOS, or just the same path on Linux —
        // canonicalize() is idempotent so the test is safe either way).
        let id = resolve_binary_id(&map_path, &dir.path().join("foo-abc123"))?;
        assert_eq!(id, "mycrate::foo");
        Ok(())
    }

    #[test]
    fn resolve_binary_id_missing_errors() -> anyhow::Result<()> {
        let dir = tempfile::tempdir()?;
        let map_path = dir.path().join("map.json");
        std::fs::write(&map_path, "{}")?;

        let err = resolve_binary_id(&map_path, Path::new("/nowhere/foo")).unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("not found"), "expected 'not found', got: {msg}");
        assert!(
            msg.contains("re-run"),
            "error should suggest re-collecting: {msg}"
        );
        Ok(())
    }

    #[test]
    fn resolve_binary_id_basename_fallback_unique() -> anyhow::Result<()> {
        // Cargo's hash drifted between the pre-run listing and the actual
        // run; the recorded path no longer matches but the target name does.
        // With a single candidate, the fallback resolves cleanly.
        let dir = tempfile::tempdir()?;
        let map_path = dir.path().join("map.json");
        let mut map: HashMap<String, String> = HashMap::new();
        map.insert(
            "/tmp/target/debug/deps/worktrunk-aaaaaaaaaaaaaaaa".to_string(),
            "worktrunk".to_string(),
        );
        std::fs::write(&map_path, serde_json::to_string(&map)?)?;

        let id = resolve_binary_id(
            &map_path,
            Path::new("/tmp/target/debug/deps/worktrunk-bbbbbbbbbbbbbbbb"),
        )?;
        assert_eq!(id, "worktrunk");
        Ok(())
    }

    #[test]
    fn resolve_binary_id_basename_fallback_ambiguous() -> anyhow::Result<()> {
        // Two crates each have a `tests/builds.rs`. Both basenames strip to
        // `builds` — the fallback won't guess; it surfaces the ambiguity.
        let dir = tempfile::tempdir()?;
        let map_path = dir.path().join("map.json");
        let mut map: HashMap<String, String> = HashMap::new();
        map.insert(
            "/tmp/target/debug/deps/builds-aaaaaaaaaaaaaaaa".to_string(),
            "mock-stub::builds".to_string(),
        );
        map.insert(
            "/tmp/target/debug/deps/builds-cccccccccccccccc".to_string(),
            "wt-perf::builds".to_string(),
        );
        std::fs::write(&map_path, serde_json::to_string(&map)?)?;

        let err = resolve_binary_id(
            &map_path,
            Path::new("/tmp/target/debug/deps/builds-bbbbbbbbbbbbbbbb"),
        )
        .unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("ambiguous"), "expected 'ambiguous', got: {msg}");
        assert!(msg.contains("mock-stub::builds"));
        assert!(msg.contains("wt-perf::builds"));
        Ok(())
    }

    #[test]
    fn target_name_strips_hash() {
        assert_eq!(target_name("worktrunk-e19bc0c52c763540"), "worktrunk");
        assert_eq!(target_name("builds-8cd2602cd0d82929"), "builds");
        assert_eq!(target_name("a-0123456789abcdef"), "a");
    }

    #[test]
    fn target_name_no_hash() {
        // Basenames without a 16-hex tail pass through unchanged.
        assert_eq!(target_name("worktrunk-build-script-build"), "worktrunk-build-script-build");
        assert_eq!(target_name("short"), "short");
        assert_eq!(target_name(""), "");
        // Tail looks hash-shaped but isn't 16 chars.
        assert_eq!(target_name("foo-abc123"), "foo-abc123");
        // Tail is 16 chars but contains non-hex.
        assert_eq!(target_name("foo-zzzzzzzzzzzzzzzz"), "foo-zzzzzzzzzzzzzzzz");
    }
}
